"""
writer.py — Writes converted Python files to the output directory,
mirrors the folder structure, and generates scaffold files.
"""

import os
from pathlib import Path

REQUIREMENTS = """\
# Python Playwright + Applitools + pytest-bdd requirements
# Generated by java2playwright agent

playwright>=1.44.0
pytest>=8.0.0
pytest-bdd>=7.0.0
pytest-playwright>=0.5.0
eyes-playwright>=1.0.0
python-dotenv>=1.0.0
""".strip()

PYTEST_INI = """\
[pytest]
# pytest-bdd feature file location
bdd_features_base_dir = features/

# Verbose output
addopts = -v --tb=short
""".strip()

DOTENV_EXAMPLE = """\
# Copy this file to .env and fill in your values
APPLITOOLS_API_KEY=your_api_key_here
USE_ULTRAFAST_GRID=true
HEADLESS=false
""".strip()

GITIGNORE = """\
.env
__pycache__/
.pytest_cache/
.venv/
venv/
*.pyc
test-results/
""".strip()

README = """\
# Converted Python Playwright + Applitools Project

Auto-generated by **java2playwright** agent from a Java Selenium + Cucumber project.

## Setup

```bash
# 1. Create and activate a virtual environment
python -m venv .venv
.venv\\Scripts\\activate        # Windows
# source .venv/bin/activate    # Mac/Linux

# 2. Install dependencies
pip install -r requirements.txt

# 3. Install Playwright browsers
playwright install chromium

# 4. Set your Applitools API key
copy .env.example .env
# Edit .env and add your APPLITOOLS_API_KEY
```

## Running tests

```bash
pytest tests/ -v
```

## Project structure

```
├── conftest.py          # Shared fixtures (Eyes, browser, runner)
├── features/            # BDD .feature files (unchanged from Java project)
├── tests/               # Converted step definition files
├── pytest.ini           # pytest configuration
├── requirements.txt     # Python dependencies
└── .env.example         # Environment variable template
```

## Notes

- Feature files are identical to the original Cucumber `.feature` files
- `conftest.py` replaces Java `@BeforeAll` / `@Before` / `@After` / `@AfterAll` hooks
- `pytest.ini` replaces `RunCucumberTest.java`
- Set `USE_ULTRAFAST_GRID=false` in `.env` to run locally without the Ultrafast Grid
""".strip()


def write_output(
    output_root: str,
    converted_files: list,  # List of (python_rel_path, python_content)
    conftest_content: str,
    feature_files: list,    # List of (java_rel_path, content) — copied as-is
) -> None:
    """
    Write all converted files and scaffold to the output directory.

    Args:
        output_root:       Root directory for the output project.
        converted_files:   List of (python_rel_path, content) tuples.
        conftest_content:  Generated conftest.py content.
        feature_files:     List of (java_rel_path, content) — feature files to copy.
    """
    root = Path(output_root)
    root.mkdir(parents=True, exist_ok=True)

    # --- Write converted Python test files ---
    for rel_path, content in converted_files:
        out_path = root / rel_path
        out_path.parent.mkdir(parents=True, exist_ok=True)
        out_path.write_text(content, encoding="utf-8")
        print(f"  [WRITE] {rel_path}")

    # --- Write feature files (unchanged, just rename to snake_case) ---
    for java_rel_path, content in feature_files:
        from scanner import java_to_python_path
        py_path = java_to_python_path(java_rel_path)
        out_path = root / py_path
        out_path.parent.mkdir(parents=True, exist_ok=True)
        out_path.write_text(content, encoding="utf-8")
        print(f"  [COPY ] {py_path}  (feature file)")

    # --- Write conftest.py ---
    conftest_path = root / "conftest.py"
    conftest_path.write_text(conftest_content, encoding="utf-8")
    print("  [WRITE] conftest.py")

    # --- Write scaffold files ---
    _write_text(root / "requirements.txt", REQUIREMENTS)
    _write_text(root / "pytest.ini", PYTEST_INI)
    _write_text(root / ".env.example", DOTENV_EXAMPLE)
    _write_text(root / ".gitignore", GITIGNORE)
    _write_text(root / "README.md", README)

    print("  [WRITE] requirements.txt, pytest.ini, .env.example, .gitignore, README.md")


def _write_text(path: Path, content: str) -> None:
    """Write text to a file, creating parent dirs as needed."""
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")


def print_summary(output_root: str) -> None:
    """Print a tree-style summary of all files written."""
    root = Path(output_root)
    print(f"\n{'='*55}")
    print(f"  Output project: {root.resolve()}")
    print(f"{'='*55}")
    for path in sorted(root.rglob("*")):
        if path.is_file():
            rel = path.relative_to(root)
            depth = len(rel.parts) - 1
            indent = "  " + "  " * depth
            print(f"{indent}{'└─ ' if depth else ''}{path.name}")
    print(f"{'='*55}")
    print("\n  Next steps:")
    print("    1. cd " + str(root.resolve()))
    print("    2. python -m venv .venv")
    print("    3. .venv\\Scripts\\activate")
    print("    4. pip install -r requirements.txt")
    print("    5. playwright install chromium")
    print("    6. copy .env.example .env  (then add your APPLITOOLS_API_KEY)")
    print("    7. pytest tests/ -v")
    print()
